# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-loto" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "e3cbbae0125c478c8e88440dbf3c28a5c6733fc29afab693df8ad1b0d4701735"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
    on_arm do
      sha256 "9a8352cc689cae7e4f5728be2ec42bac77ae01572476ccaa4bf8e1a09291eaeb"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3f6956f2fd8bbb9fd6cc33fc91bf35da455b850823822b8f299dac387382eaf"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
    on_arm do
      sha256 "e2d9a9e78f638802b84f361dfb3509bd22f7a833fb6430a5dd11b466cca3666c"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
  end

  name "go-loto"
  desc "API des tirages Loto FDJ"
  homepage "https://github.com/Olprog59/go-loto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-loto"

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-loto"]
  end

  # No zap stanza required

end
