# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-loto" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c5a229aca2bfa42bfc9d4510fab40580cb6a9943c722bfd9a7ce6f46ab6d0727"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
    on_arm do
      sha256 "910dd8c8241d2fd0f3217d51c4a8ed0567451606317a821483fe324a4acd188c"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7bcc54e5276da2a9cb682cce6028b19c26cd13c3eaaedd831e8f1fc983f6f3e"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
    on_arm do
      sha256 "1fcf16093b1f1826f6e7435cadc73ab7adcb15548630f290811fb0fdce958f4c"
      url "https://github.com/Olprog59/go-loto/releases/download/v#{version}/go-loto_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Olprog59/go-loto"
    end
  end

  name "go-loto"
  desc "API des tirages Loto FDJ"
  homepage "https://github.com/Olprog59/go-loto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-loto"

  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-loto"]
  end

  # No zap stanza required

end
